export const FETCH_UNIVERSITIES = "FETCH_UNIVERSITIES";
export const SEARCH_UNIVERSITIES = "SEARCH_UNIVERSITIES";
export const FILTER_UNIVERSITIES = "FILTER_UNIVERSITIES";
export const LOADING = "LOADING";
